// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RouteServer.proto

#ifndef PROTOBUF_INCLUDED_RouteServer_2eproto
#define PROTOBUF_INCLUDED_RouteServer_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "BaseDefine.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_RouteServer_2eproto 

namespace protobuf_RouteServer_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_RouteServer_2eproto
namespace RouteServer {
class UserInfo;
class UserInfoDefaultTypeInternal;
extern UserInfoDefaultTypeInternal _UserInfo_default_instance_;
}  // namespace RouteServer
namespace google {
namespace protobuf {
template<> ::RouteServer::UserInfo* Arena::CreateMaybeMessage<::RouteServer::UserInfo>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace RouteServer {

// ===================================================================

class UserInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:RouteServer.UserInfo) */ {
 public:
  UserInfo();
  virtual ~UserInfo();

  UserInfo(const UserInfo& from);

  inline UserInfo& operator=(const UserInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  UserInfo(UserInfo&& from) noexcept
    : UserInfo() {
    *this = ::std::move(from);
  }

  inline UserInfo& operator=(UserInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const UserInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UserInfo* internal_default_instance() {
    return reinterpret_cast<const UserInfo*>(
               &_UserInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(UserInfo* other);
  friend void swap(UserInfo& a, UserInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline UserInfo* New() const final {
    return CreateMaybeMessage<UserInfo>(NULL);
  }

  UserInfo* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<UserInfo>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const UserInfo& from);
  void MergeFrom(const UserInfo& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UserInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string msg_server_name = 2;
  void clear_msg_server_name();
  static const int kMsgServerNameFieldNumber = 2;
  const ::std::string& msg_server_name() const;
  void set_msg_server_name(const ::std::string& value);
  #if LANG_CXX11
  void set_msg_server_name(::std::string&& value);
  #endif
  void set_msg_server_name(const char* value);
  void set_msg_server_name(const char* value, size_t size);
  ::std::string* mutable_msg_server_name();
  ::std::string* release_msg_server_name();
  void set_allocated_msg_server_name(::std::string* msg_server_name);

  // .BaseDefine.ClientType client_type = 1;
  void clear_client_type();
  static const int kClientTypeFieldNumber = 1;
  ::BaseDefine::ClientType client_type() const;
  void set_client_type(::BaseDefine::ClientType value);

  // @@protoc_insertion_point(class_scope:RouteServer.UserInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr msg_server_name_;
  int client_type_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_RouteServer_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// UserInfo

// .BaseDefine.ClientType client_type = 1;
inline void UserInfo::clear_client_type() {
  client_type_ = 0;
}
inline ::BaseDefine::ClientType UserInfo::client_type() const {
  // @@protoc_insertion_point(field_get:RouteServer.UserInfo.client_type)
  return static_cast< ::BaseDefine::ClientType >(client_type_);
}
inline void UserInfo::set_client_type(::BaseDefine::ClientType value) {
  
  client_type_ = value;
  // @@protoc_insertion_point(field_set:RouteServer.UserInfo.client_type)
}

// string msg_server_name = 2;
inline void UserInfo::clear_msg_server_name() {
  msg_server_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& UserInfo::msg_server_name() const {
  // @@protoc_insertion_point(field_get:RouteServer.UserInfo.msg_server_name)
  return msg_server_name_.GetNoArena();
}
inline void UserInfo::set_msg_server_name(const ::std::string& value) {
  
  msg_server_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:RouteServer.UserInfo.msg_server_name)
}
#if LANG_CXX11
inline void UserInfo::set_msg_server_name(::std::string&& value) {
  
  msg_server_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:RouteServer.UserInfo.msg_server_name)
}
#endif
inline void UserInfo::set_msg_server_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  msg_server_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:RouteServer.UserInfo.msg_server_name)
}
inline void UserInfo::set_msg_server_name(const char* value, size_t size) {
  
  msg_server_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:RouteServer.UserInfo.msg_server_name)
}
inline ::std::string* UserInfo::mutable_msg_server_name() {
  
  // @@protoc_insertion_point(field_mutable:RouteServer.UserInfo.msg_server_name)
  return msg_server_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UserInfo::release_msg_server_name() {
  // @@protoc_insertion_point(field_release:RouteServer.UserInfo.msg_server_name)
  
  return msg_server_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UserInfo::set_allocated_msg_server_name(::std::string* msg_server_name) {
  if (msg_server_name != NULL) {
    
  } else {
    
  }
  msg_server_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), msg_server_name);
  // @@protoc_insertion_point(field_set_allocated:RouteServer.UserInfo.msg_server_name)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace RouteServer

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_RouteServer_2eproto
